spring:

  datasource:

   url: jdbc:mysql://192.168.131.1:3306/estate?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai

   username: root

   password: 123456

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
    cache: false
